# **Assignment-1 : Numpy**

In [6]:
import numpy as np

### **Question 1: Create a null vector of size 10 but the fifth value which is 1.**

In [9]:
# create a null vector of size 10
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)
print(" The fifth value which is : ", null_vector[4])

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 The fifth value which is :  1.0


### **Question 2: Create a vector with values ranging from 10 to 49.**

In [8]:
a_vector = np.arange(10,50)
print("The values : ", a_vector)

The values :  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### **Question 3 :  Create a 3x3 matrix with values ranging from 0 to 8**

In [10]:
matrix = np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### **Question 4 : Find indices of non-zero elements from [1,2,0,0,4,0]**

In [11]:
non_zero_elements = np.nonzero([1,2,0,0,4,0]) 
print(non_zero_elements)

(array([0, 1, 4], dtype=int64),)


### **Question 5 : Create a 10x10 array with random values and find the minimum and maximum values.**

In [19]:
a = np.random.random((10,10))
amin = a.min()
amax = a.max()
print(amin,amax)


0.010582861444757397 0.9597927833226733


### **Question 6 : Create a random vector of size 30 and find the mean value.**

In [20]:
random_vector = np.random.random(30)
mean_vector = random_vector.mean()
print(mean_vector)

0.4851644628103289
